language: node_js
node_js:
- "stable"
install:
  - npm install
services:
  - postgresql
script:
  - npm test
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
before_script:
  - createuser olubori -s -U postgres
  - createdb we_connect_test --username=olubori
  - sequelize db:migrate
  - sequelize db:seed:all
after_success :
    - npm run coverage